import React, { useState, useEffect } from 'react'

export default function SocialProof() {
  const [patternCount, setPatternCount] = useState(0)
  const [makerCount, setMakerCount] = useState(0)
  const [projectCount, setProjectCount] = useState(0)

  useEffect(() => {
    const animateCounter = (target: number, setter: (val: number) => void, duration: number = 2000) => {
      let start = 0
      const increment = target / (duration / 16)
      const timer = setInterval(() => {
        start += increment
        if (start >= target) {
          setter(target)
          clearInterval(timer)
        } else {
          setter(Math.floor(start))
        }
      }, 16)
    }

    const observer = new IntersectionObserver((entries) => {
      entries.forEach(entry => {
        if (entry.isIntersecting) {
          animateCounter(12500, setPatternCount)
          animateCounter(8300, setMakerCount)
          animateCounter(45000, setProjectCount)
          observer.disconnect()
        }
      })
    })

    const element = document.getElementById('social-proof')
    if (element) observer.observe(element)

    return () => observer.disconnect()
  }, [])

  return (
    <section id="social-proof" className="px-6 py-16 relative">
      <div className="max-w-7xl mx-auto">
        <div
          className="rounded-3xl p-12 md:p-16 relative overflow-hidden"
          style={{
            background: 'linear-gradient(135deg, rgba(199, 169, 255, 0.1) 0%, rgba(152, 225, 179, 0.1) 100%)',
            border: '2px solid #E9E2FF'
          }}
        >
          <div className="absolute top-0 right-0 w-64 h-64 rounded-full opacity-10 blur-3xl"
            style={{ background: '#C7A9FF' }}
          />

          <div className="relative z-10">
            <div className="text-center mb-12">
              <h2 className="text-3xl md:text-4xl font-bold mb-3" style={{ color: '#2B244D' }}>
                Trusted by Thousands of Makers
              </h2>
              <p className="text-lg" style={{ color: '#6F679E' }}>
                Join the growing community of crochet enthusiasts creating amazing patterns
              </p>
            </div>

            <div className="grid md:grid-cols-3 gap-8">
              <div className="text-center">
                <div
                  className="text-5xl md:text-6xl font-bold mb-2"
                  style={{
                    background: 'linear-gradient(135deg, #C7A9FF 0%, #A484FF 100%)',
                    WebkitBackgroundClip: 'text',
                    WebkitTextFillColor: 'transparent',
                    backgroundClip: 'text'
                  }}
                >
                  {patternCount.toLocaleString()}+
                </div>
                <div className="text-lg font-semibold mb-1" style={{ color: '#2B244D' }}>
                  Patterns Created
                </div>
                <div className="text-sm" style={{ color: '#6F679E' }}>
                  Designed and generated by our community
                </div>
              </div>

              <div className="text-center">
                <div
                  className="text-5xl md:text-6xl font-bold mb-2"
                  style={{
                    background: 'linear-gradient(135deg, #98E1B3 0%, #C7A9FF 100%)',
                    WebkitBackgroundClip: 'text',
                    WebkitTextFillColor: 'transparent',
                    backgroundClip: 'text'
                  }}
                >
                  {makerCount.toLocaleString()}+
                </div>
                <div className="text-lg font-semibold mb-1" style={{ color: '#2B244D' }}>
                  Active Makers
                </div>
                <div className="text-sm" style={{ color: '#6F679E' }}>
                  Creating beautiful crochet projects
                </div>
              </div>

              <div className="text-center">
                <div
                  className="text-5xl md:text-6xl font-bold mb-2"
                  style={{
                    background: 'linear-gradient(135deg, #A484FF 0%, #98E1B3 100%)',
                    WebkitBackgroundClip: 'text',
                    WebkitTextFillColor: 'transparent',
                    backgroundClip: 'text'
                  }}
                >
                  {projectCount.toLocaleString()}+
                </div>
                <div className="text-lg font-semibold mb-1" style={{ color: '#2B244D' }}>
                  Stitches Calculated
                </div>
                <div className="text-sm" style={{ color: '#6F679E' }}>
                  Precisely computed for perfect results
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
